ignore-paths:
  - venv
  - .venv
  - env
  - migrations
  - __pycache__
  - static
  - templates
  - .git

uses:
  - pyflakes
  - pep8
  - mccabe
  - dodgy

without:
  - pylint

pep8:
  max-line-length: 120

strictness: medium
